name = "baby-food-cube-management"
compatibility_date = "2026-07-03"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "baby-food-cube"
database_id = "4baf0d0d-cfd2-4391-bdb1-6fe1ca5b8bcd"
